# INFO: This extension requires webgl in order to work, webgl is a significan fingerprinting vector and therefore must be enabled only on trusted websites. Finish this implementation later. Also, consider implementing sandboxing for firenvim: https://github.com/glacambre/firenvim/blob/master/SECURITY.md
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.nixvim.plugins.lualine;
  inherit (pkgs.firefox-addons) firenvim;
  nvim = lib.getExe config.programs.nixvim.build.package;
in
{
  programs = {
    nixvim = {
      plugins.firenvim = {
        enable = true;
        settings.localSettings = {
          ".*" = {
            cmdline = "neovim";
            content = "text";
            priority = 0;
            selector = "textarea";
            takeover = "always";
          };
        };
      };

      autoCmd = [
        {
          event = "UIEnter";
          callback = {
            __raw =
              # lua
              ''
                function(event)
                  local client = vim.api.nvim_get_chan_info(vim.v.event.chan).client
                  if client ~= nil and client.name == "Firenvim" then
                    vim.o.laststatus = 0
                    vim.o.showtabline = 0
                    ${lib.optionalString cfg.enable "require('lualine').hide()"}
                  end
                end
              '';
          };
        }
      ];
    };

    # INFO: Firenvim needs the `nativeMessaging` and `<all_urls>` permissions to
    # start Neovim and to inject its iframe. Sideloading the extension via
    # `extensions.packages` does not grant those install-time permissions, so
    # install it through the enterprise ExtensionSettings policy instead,
    # which auto-grants them and auto-enables the addon.
    librewolf.policies.ExtensionSettings.${firenvim.addonId} = {
      installation_mode = "force_installed";
      install_url = "file://${firenvim.src}";
    };
  };

  # INFO: Firenvim talks to Neovim through a native messaging host: a manifest
  # (`~/.librewolf/native-messaging-hosts/firenvim.json`) pointing at a launcher
  # script that starts Neovim with `firenvim#run()`. Both are generated by
  # `firenvim#install`, which has to run against the freshly built Neovim so the
  # launcher resolves to a valid store path. Run it on every activation (and
  # therefore every boot, considering `~/.local/share/firenvim` lives on an
  # ephemeral volume) to keep them in sync with the current generation.
  home.activation.setupFirenvim =
    lib.hm.dag.entryAfter [ "writeBoundary" ]
      # bash
      ''
        if ! ${nvim} --headless -c "call firenvim#install(0)" -c "qa!"; then
          echo "Warning: firenvim#install failed; the Firenvim native messaging host was not regenerated." >&2
        fi
      '';
}
