{
  config,
  lib,
  pkgs,
  ...
}:
with lib;
let
  cfg = config.programs.wezterm;

  inherit (import ./_plugins.nix { inherit cfg lib; })
    plainPlugins
    pluginListShim
    registeredPlugins
    ;
in
{
  config = mkIf cfg.enable {
    home.packages = [ cfg.package ];

    xdg.configFile =
      let
        tomlFormat = pkgs.formats.toml { };
      in
      mkMerge [
        # 1. The Main `wezterm.lua` Entry Point
        {
          "wezterm/wezterm.lua".text = ''
            -- Generated by Home Manager.
            -- See https://wezfurlong.org/wezterm/

            local wezterm = require 'wezterm'
            local config = wezterm.config_builder() -- [[@as Wezterm]]

            ${pluginListShim}

            ${
              mapAttrsToList (name: _: ''require("modules.${name}").apply_to_config(config)'') cfg.extraConfig
              |> concatLines
            }

            return config
          '';
        }

        # 2. The Dynamic Modules (mapped from extraConfig)
        (mapAttrs' (
          name: value:
          let
            # Convert "keybinds.overrides" -> "keybinds/overrides"
            pathName = replaceStrings [ "." ] [ "/" ] name;
            targetPath = "wezterm/modules/${pathName}.lua";
          in
          # Check if value is a path (source) or string (text)
          nameValuePair targetPath (if isPath value then { source = value; } else { text = value; })
        ) cfg.extraConfig)

        # 3. Color Schemes (Existing logic)
        (mapAttrs' (
          name: value:
          nameValuePair "wezterm/colors/${name}.toml" {
            source = tomlFormat.generate "${name}.toml" { colors = value; };
          }
        ) cfg.colorSchemes)

        # INFO: 4. WezTerm plugins — symlinked into $XDG_CONFIG_HOME/wezterm/plugins/
        # Plain form: plugins/<name>/ -> <src>/plugin
        (mapAttrs' (
          name: src:
          nameValuePair "wezterm/plugins/${name}" {
            source = "${src}/plugin";
          }
        ) plainPlugins)

        # INFO: Registry form — official URL-encoded layout, resolvable by
        # plugins that consult wezterm.plugin.list()
        # Plain name alias for require("plugins.<name>") is kept so Lua
        # code does not need to know the encoded name.
        (mapAttrs' (
          _: p:
          nameValuePair "wezterm/plugins/${p.dir}/plugin" {
            source = "${p.src}/plugin";
          }
        ) registeredPlugins)
        (mapAttrs' (
          name: p:
          nameValuePair "wezterm/plugins/${name}" {
            source = "${p.src}/plugin";
          }
        ) registeredPlugins)
      ];

    programs =
      let
        shellIntegrationStr = ''
          source "${cfg.package}/etc/profile.d/wezterm.sh"
        '';
      in
      {
        bash.initExtra = mkIf cfg.enableBashIntegration shellIntegrationStr;
        zsh.initContent = mkIf cfg.enableZshIntegration shellIntegrationStr;
      };
  };
}
