{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:
with lib;
let
  cfg = config.programs.wezterm;

  # INFO: WezTerm's plugin manager encodes repo URLs into directory names
  # (see wezterm's config-registry encoding). Reproduced here so plugins
  # installed via the generated shim resolve like official clones.
  encodePluginUrl =
    url: replaceStrings [ ":" "/" "\\" "." "%" ] [ "sCs" "sZs" "sBs" "sDs" "sPs" ] url;

  # INFO: Infer canonical repository URLs from flake.lock. Flake input
  # attrsets do not carry owner/repo, but each lock node records the
  # original ref ({ type = "github"; owner; repo; }) and the locked rev.
  # flake.lock is guaranteed consistent with flake.nix at evaluation time
  # (nix relocks mismatched inputs before evaluating); only --override-input
  # can desynchronize them, which simply misses here -> plain plugin.
  urlByRev =
    inputs.self
    |> (self: fromJSON (readFile "${self}/flake.lock"))
    |> (lock: removeAttrs lock.nodes [ "root" ])
    |> mapAttrs (
      _: node:
      let
        o = node.original or { };
      in
      if o.type == "github" || o.type == "gitlab" then
        {
          rev = (node.locked.rev or null);
          url = "https://${o.type}.com/${o.owner}/${o.repo}";
        }
      else
        {
          rev = null;
          url = null;
        }
    )
    |> attrValues
    |> filter (e: e.rev != null && e.url != null)
    |> map (e: nameValuePair e.rev e.url)
    |> listToAttrs;

  # Classify each plugin: explicit { url, src } overrides; attrsets carrying
  # a locked rev are matched against urlByRev (bare flake inputs); everything
  # else (paths, unmatched inputs) stays plain. NOTE: bare flake inputs are
  # path-coercible attrsets (outPath, rev, ...), not real paths.
  registeredPlugins =
    cfg.plugins
    |> mapAttrs' (
      name: v:
      if isAttrs v && v ? url && v ? src then
        nameValuePair name { inherit (v) url src; }
      else if isAttrs v && v ? rev && urlByRev ? ${v.rev} then
        nameValuePair name {
          url = urlByRev.${v.rev};
          src = v;
        }
      else
        nameValuePair name null
    )
    |> filterAttrs (_: r: r != null);

  plainPlugins = filterAttrs (
    _: v: !((isAttrs v && v ? url && v ? src) || (isAttrs v && v ? rev && urlByRev ? ${v.rev}))
  ) cfg.plugins;

  # INFO: Lua shim making require()-loaded plugins visible to
  # wezterm.plugin.list(), for plugins that assume installation via
  # wezterm's built-in plugin manager.
  pluginListShim =
    registeredPlugins
    |> mapAttrsToList (
      _: p:
      "{ plugin = '${p.url}', plugin_dir = wezterm.config_dir .. '/plugins/${encodePluginUrl p.url}', component = '${encodePluginUrl p.url}' },"
    )
    |> concatStringsSep "\n"
    |> (
      entries:
      optionalString (entries != "") ''
        local __real_plugin_list = wezterm.plugin.list
        wezterm.plugin.list = function()
          local plugins = __real_plugin_list()
          for _, entry in ipairs({
            ${entries}
          }) do
            plugins[#plugins + 1] = entry
          end
          return plugins
        end
      ''
    );
in
{
  config = mkIf cfg.enable {
    home.packages = [ cfg.package ];

    xdg.configFile =
      let
        tomlFormat = pkgs.formats.toml { };
      in
      mkMerge [
        # 1. The Main `wezterm.lua` Entry Point
        {
          "wezterm/wezterm.lua".text = ''
            -- Generated by Home Manager.
            -- See https://wezfurlong.org/wezterm/

            local wezterm = require 'wezterm'
            local config = wezterm.config_builder() -- [[@as Wezterm]]

            ${pluginListShim}

            ${
              mapAttrsToList (name: _: ''require("modules.${name}").apply_to_config(config)'') cfg.extraConfig
              |> concatLines
            }

            return config
          '';
        }

        # 2. The Dynamic Modules (mapped from extraConfig)
        (mapAttrs' (
          name: value:
          let
            # Convert "keybinds.overrides" -> "keybinds/overrides"
            pathName = replaceStrings [ "." ] [ "/" ] name;
            targetPath = "wezterm/modules/${pathName}.lua";
          in
          # Check if value is a path (source) or string (text)
          nameValuePair targetPath (if isPath value then { source = value; } else { text = value; })
        ) cfg.extraConfig)

        # 3. Color Schemes (Existing logic)
        (mapAttrs' (
          name: value:
          nameValuePair "wezterm/colors/${name}.toml" {
            source = tomlFormat.generate "${name}.toml" { colors = value; };
          }
        ) cfg.colorSchemes)

        # INFO: 4. WezTerm plugins — symlinked into $XDG_CONFIG_HOME/wezterm/plugins/
        # Plain form: plugins/<name>/ -> <src>/plugin
        (mapAttrs' (
          name: src:
          nameValuePair "wezterm/plugins/${name}" {
            source = "${src}/plugin";
          }
        ) plainPlugins)

        # INFO: Registry form — official URL-encoded layout, resolvable by
        # plugins that consult wezterm.plugin.list()
        # Plain name alias for require("plugins.<name>") is kept so Lua
        # code does not need to know the encoded name.
        (mapAttrs' (
          _: p:
          let
            encoded = encodePluginUrl p.url;
          in
          nameValuePair "wezterm/plugins/${encoded}/plugin" {
            source = "${p.src}/plugin";
          }
        ) registeredPlugins)
        (mapAttrs' (
          name: p:
          nameValuePair "wezterm/plugins/${name}" {
            source = "${p.src}/plugin";
          }
        ) registeredPlugins)
      ];

    programs =
      let
        shellIntegrationStr = ''
          source "${cfg.package}/etc/profile.d/wezterm.sh"
        '';
      in
      {
        bash.initExtra = mkIf cfg.enableBashIntegration shellIntegrationStr;
        zsh.initContent = mkIf cfg.enableZshIntegration shellIntegrationStr;
      };
  };
}
